### ISSUE TITLE
Error: Invalid schema content: (nameIdFormat.$_root.alternatives) 

### ISSUE THREAD

**Issue by gigabytejayesh** [toriihq/hapi-saml2#3]
Hi,
Our existing codebase has the following Hapi dependency,

- "@hapi/hapi": "^18.4.0",
- "@hapi/joi": "^16.1.8",

Getting error **Error: Invalid schema content: (nameIdFormat.$_root.alternatives)** while using @hapi/joi version **^16.1.8**
Also, checked for the lower version works till @hapi/joi **15.1.1**

Is there any plan to release new versions that support the latest Hapi libraries.

**Comment by berzniz** [comment]
Hi @gigabytejayesh 

It is currently supporting `@hapi/joi` 15 because that's what we use.

As `Joi` leaving `hapi` (see here: https://github.com/sideway/joi/issues/2411) it is quite hard to understand what version should be chosen here and I don't want to implement multiple versions for each Joi.

We only have a use of `Joi.string().required()` which should be the same on all versions. Can you spot what isn't compatible with Joi 16 here? There's an option to get `Joi` as a dependency in the config and use it. Do you think that would be a valid solution?

**Comment by berzniz** [comment]
Latest update should allow for any version of Joi/Boom (bring your own version...)
